// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: orders.sql

package sqlc

import (
	"context"
	"time"
)

const addOrderItem = `-- name: AddOrderItem :exec
INSERT INTO order_items (order_id, product_id, quantity, price)
VALUES ($1, $2, $3, $4)
`

type AddOrderItemParams struct {
	OrderID   int32
	ProductID int32
	Quantity  int32
	Price     string
}

func (q *Queries) AddOrderItem(ctx context.Context, arg AddOrderItemParams) error {
	_, err := q.db.ExecContext(ctx, addOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.Price,
	)
	return err
}

const cancelOrder = `-- name: CancelOrder :exec
UPDATE orders
SET status = 'Cancelled', updated_at = NOW()
WHERE id = $1 AND status = 'Pending'
RETURNING id, user_id, total, status, updated_at
`

func (q *Queries) CancelOrder(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, cancelOrder, id)
	return err
}

const createOrder = `-- name: CreateOrder :one
SELECT id, user_id, total, status FROM orders WHERE user_id = $1
`

type CreateOrderRow struct {
	ID     int32
	UserID int32
	Total  string
	Status string
}

func (q *Queries) CreateOrder(ctx context.Context, userID int32) (CreateOrderRow, error) {
	row := q.db.QueryRowContext(ctx, createOrder, userID)
	var i CreateOrderRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Total,
		&i.Status,
	)
	return i, err
}

const getOrderById = `-- name: GetOrderById :one
INSERT INTO orders (user_id, total, status)
VALUES ($1, $2, 'Pending')
RETURNING id, user_id, total, status, created_at
`

type GetOrderByIdParams struct {
	UserID int32
	Total  string
}

type GetOrderByIdRow struct {
	ID        int32
	UserID    int32
	Total     string
	Status    string
	CreatedAt time.Time
}

func (q *Queries) GetOrderById(ctx context.Context, arg GetOrderByIdParams) (GetOrderByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getOrderById, arg.UserID, arg.Total)
	var i GetOrderByIdRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Total,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateOrderStatusParams struct {
	Status string
	ID     int32
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderStatus, arg.Status, arg.ID)
	return err
}

const updateOrderTotal = `-- name: UpdateOrderTotal :exec
UPDATE orders
SET total = (
    SELECT SUM(price * quantity)
    FROM order_items
    WHERE order_id = $1
), updated_at = NOW()
WHERE id = $1
RETURNING id, total, status, updated_at
`

func (q *Queries) UpdateOrderTotal(ctx context.Context, orderID int32) error {
	_, err := q.db.ExecContext(ctx, updateOrderTotal, orderID)
	return err
}
