// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	AddOrderItem(ctx context.Context, arg AddOrderItemParams) error
	CancelOrder(ctx context.Context, id int32) (CancelOrderRow, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error)
	CreateSeederHistory(ctx context.Context, seederName string) error
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteProduct(ctx context.Context, id int32) error
	GetAdmins(ctx context.Context) ([]GetAdminsRow, error)
	GetOrderById(ctx context.Context, id int32) (GetOrderByIdRow, error)
	GetOrderItems(ctx context.Context, orderID int32) ([]GetOrderItemsRow, error)
	GetOrdersByUserId(ctx context.Context, userID int32) ([]Order, error)
	GetProductById(ctx context.Context, id int32) (GetProductByIdRow, error)
	GetProducts(ctx context.Context) ([]GetProductsRow, error)
	GetSeederByName(ctx context.Context, seederName string) (string, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdateOrderTotal(ctx context.Context, orderID int32) (UpdateOrderTotalRow, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error)
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) error
}

var _ Querier = (*Queries)(nil)
