// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: seeder_history.sql

package sqlc

import (
	"context"
)

const createSeederHistory = `-- name: CreateSeederHistory :exec
INSERT INTO seeding_history (seeder_name) VALUES ($1)
`

func (q *Queries) CreateSeederHistory(ctx context.Context, seederName string) error {
	_, err := q.db.ExecContext(ctx, createSeederHistory, seederName)
	return err
}

const getSeederByName = `-- name: GetSeederByName :one
SELECT seeder_name FROM seeding_history WHERE seeder_name = $1
`

func (q *Queries) GetSeederByName(ctx context.Context, seederName string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSeederByName, seederName)
	var seeder_name string
	err := row.Scan(&seeder_name)
	return seeder_name, err
}
